#!/usr/bin/env bash
#telling passwd story

while IFS=: read -r username password uid gid _ homedir shell; do
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd
