#!/usr/bin/env bash
#Parses Apache log files in list format
LOG_FILE="apache-access.log"

if [[ ! -f $LOG_FILE ]]; then
    echo "Log file not found: $LOG_FILE"
    exit 1
fi

awk '{print $1, $9}' "$LOG_FILE" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
