#!/usr/bin/env bash
#Parses Apache log files in list format
LOG_FILE="apache-access.log"

if [[ -f $LOG_FILE ]]; then
   awk '{print $1, $9}' "$LOG_FILE" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
fi
