#!/usr/bin/env bash
#information on school file
filename="school"

if [ -e $filename ];then
    echo "school file exists"
    if [ -z $filename ];then
	    echo "school file is empty"
	    if [ -f $filename ];then
		    echo "school is a regular file"
	    else
		    echo "(nothing)"
   	    fi
    else
	    echo "school file is not empty"
    fi
else
	echo "school file doesn't exist"
fi
