#!/usr/bin/env bash
#information on school file
filename="school"

if [ -e $filename ];then
    echo "File exists"
else
    echo "File doesn't exist"
fi
if [ -z $filename ];then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f $filename ];then
	echo "school is a regular files."
else
	echo "(nothing)"
fi
